"""Add vocal_file_path to recordings table

Revision ID: 370059d9bf57
Revises: 889b402fc9f8
Create Date: 2025-12-03 10:26:35.954255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370059d9bf57'
down_revision: Union[str, None] = '889b402fc9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('vocal_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'vocal_file_path')
    # ### end Alembic commands ###