"""Initial migration

Revision ID: 658af4c97eb5
Revises: 2cc91f1c75ea
Create Date: 2025-12-01 00:20:06.435003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658af4c97eb5'
down_revision: Union[str, None] = '2cc91f1c75ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###